### ISSUE TITLE
when I try to click on a link Launch iDrop Desktop in my sidebar, I  got 404 error 

### ISSUE THREAD

**Issue by ganqqwerty** [INCF/ids-tools#11]
The link is here: http://dl.dropbox.com/u/935446/Selection_008.png

**Comment by brainstorm** [comment]
@michael-conway, I suspect that this one is related with issue #12 and has to do with some broken apache/tomcat URL routing since when I try to access the `.jnlp` directly via:

https://ids-eu.incf.net/idrop-release

I get:

```
$ tail /var/log/apache2/ssl_access.log
 - - [03/Jul/2014:13:52:49 +0000] "GET /idrop-release HTTP/1.1" 404 5219 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"
```

But the files are there and correctly pointed by apache directives:

```
$ ls -alh /srv/irods/www/idrop-release/idrop.jnlp
-rw-r--r-- 1 root root 2.0K Oct 12  2012 /srv/irods/www/idrop-release/idrop.jnlp

$ cat /etc/apache2/sites-enabled/irod-web-ssl
(...)
  <Directory /srv/irods/www/idrop-release>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    allow from all
  </Directory>
```

Do you have any canonical tomcat/apache config files for `irods-web`?

@raphael-ritz, can you shed some light into this issue? :)

**Comment by michael-conway** [comment]
Hey roman,

I've gone into idrop and totally removed any reference to jnlp files from
that 'tools/iDrop desktop' link, instead it is to present a web page with
links to the various installers, so that webstart is not even an option.

WebStart is so horribly broken that it had hamstrung iDrop Desktop.

**Comment by brainstorm** [comment]
Alright, good to hear we're cutting back on complexity. Then I'll wait or try to fix this one:

https://github.com/DICE-UNC/idrop/issues/26

So that I can deploy a newer "stable" version that users can use (critically, issue #12).
