### ISSUE TITLE
ids-init behaviour and irodsEnv management

### ISSUE THREAD

**Issue by brainstorm** [INCF/ids-tools#9]
Issue reported by "Neil Edward" from the Australian node:

When one runs ids-init it assumes the server is ids.incf.net (and there is no command line argument to change it).

If one’s data is not hosted there (my test data is available only on ids-eu.incf.net), how does
one change the host.

Is the only methodology to edit the .irods/.irodsEnv file ?

**Comment by cansmith** [comment]
Since ids-init's use if for setting up use of the IDS, I think it's proper to assume the server is ids.incf.net, since this entry point will connect you to your geographically closest IDS server (for instance, ids-eu.incf.net if you are in Europe). So I don't see this as a problem. 

If the host needs to be changed then people can just edit .irods/.irodsEnv.
